baseurl: "/"
languageCode: "en-us"
title: "Milena Suarez Castillo Academic Website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/cv/:year/:month/:day/:slug/"
  post: "/categories/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: News
      url: "news/"
      weight: 2

params:
  description: "Links to my work"
  footer: "Built with the help of &copy; [Yihui Xie](https://yihui.org) 2017 -- 2020"

markup:
  goldmark:
    renderer:
      unsafe: true
